// DEFINIZIONI PAZIENTE
#define LEN_CODICEFISCALE 17
#define LEN_NOME 12
#define LEN_COGNOME 12
#define LEN_PASSWORD 15
#define LEN_SINTOMI 128
#define LEN_GIORNATA 11
#define LEN_TITOLOCONSOLE 100

// DEFINIZIONI DIPENDENTE
#define LEN_NOME_DIPENDENTE 12
#define LEN_COGNOME_DIPENDENTE 12
#define LEN_USERID_DIPENDENTE 10
#define LEN_PASSWORD_DIPENDENTE 15

// DEFINIZIONI DIPENDENTE-GESTIONE LISTE/ARRAY
#define LEN_DATATEST 11
#define LEN_ORARIOTEST 11
#define LEN_ESITO 9
